"""The operation inventory: this plan's tables transcribed as data.

`OPS` is the machine-readable contract - one row per operation, fixed by the
v2.5-build plan and the prompts-and-agent-activity follow-on (op name, risk
group, generated-module, HTTP method, path). `litellm_version` is hand-written
(ROOT) and lives outside the inventory, so `len(OPS) == 209`. Transcribe
EXACTLY: names/endpoints come from the plan's
tables, methods from the snapshot. A row that does not resolve against the
snapshot is a generation-time error naming the op.
"""

from __future__ import annotations

from typing import NamedTuple


class Op(NamedTuple):
    name: str
    group: str  # read | write | execute | delete | admin
    module: str  # read_core | read_infra | write | execute | delete | admin | platform | prompts
    method: str  # GET | POST | PUT | PATCH | DELETE
    path: str


# File emission order of the generated modules.
MODULES: tuple[str, ...] = (
    "read_core",
    "read_infra",
    "write",
    "execute",
    "delete",
    "admin",
    "platform",
    "prompts",
)

# Risk group -> the Group variable name in tools/groups.py.
GROUP_VARS: dict[str, str] = {
    "read": "litellm_read",
    "write": "litellm_write",
    "execute": "litellm_execute",
    "delete": "litellm_delete",
    "admin": "litellm_admin",
}

OPS: tuple[Op, ...] = (
    # --- read_core (20): keys / teams / users / orgs / customers / budgets ---
    Op("list_keys", "read", "read_core", "GET", "/key/list"),
    Op("key_info", "read", "read_core", "GET", "/key/info"),
    Op("key_health", "read", "read_core", "POST", "/key/health"),
    Op("list_teams", "read", "read_core", "GET", "/v2/team/list"),
    Op("team_info", "read", "read_core", "GET", "/team/info"),
    Op("team_daily_activity", "read", "read_core", "GET", "/team/daily/activity"),
    Op("team_permissions", "read", "read_core", "GET", "/team/permissions_list"),
    Op("team_callbacks", "read", "read_core", "GET", "/team/{team_id}/callback"),
    Op("list_users", "read", "read_core", "GET", "/user/list"),
    Op("user_info", "read", "read_core", "GET", "/user/info"),
    Op("user_daily_activity", "read", "read_core", "GET", "/user/daily/activity"),
    Op("list_organizations", "read", "read_core", "GET", "/organization/list"),
    Op("organization_info", "read", "read_core", "GET", "/organization/info"),
    Op("organization_daily_activity", "read", "read_core", "GET", "/organization/daily/activity"),
    Op("list_customers", "read", "read_core", "GET", "/customer/list"),
    Op("customer_info", "read", "read_core", "GET", "/customer/info"),
    Op("customer_daily_activity", "read", "read_core", "GET", "/customer/daily/activity"),
    Op("list_budgets", "read", "read_core", "GET", "/budget/list"),
    Op("budget_info", "read", "read_core", "POST", "/budget/info"),
    Op("budget_settings", "read", "read_core", "GET", "/budget/settings"),
    # --- read_infra (47): models / creds / tags / guardrails / spend / audit /
    #     health / settings / utils / mcp-registry / public ---
    Op("list_models", "read", "read_infra", "GET", "/v1/models"),
    Op("model_info", "read", "read_infra", "GET", "/v2/model/info"),
    Op("get_model", "read", "read_infra", "GET", "/v1/models/{model_id}"),
    Op("model_group_info", "read", "read_infra", "GET", "/model_group/info"),
    Op("list_access_groups", "read", "read_infra", "GET", "/v1/access_group"),
    Op("access_group_info", "read", "read_infra", "GET", "/v1/access_group/{access_group_id}"),
    Op("list_credentials", "read", "read_infra", "GET", "/credentials"),
    Op("get_credential", "read", "read_infra", "GET", "/credentials/by_name/{credential_name}"),
    Op("credential_by_model", "read", "read_infra", "GET", "/credentials/by_model/{model_id}"),
    Op("list_tags", "read", "read_infra", "GET", "/tag/list"),
    Op("tag_info", "read", "read_infra", "POST", "/tag/info"),
    Op("tag_daily_activity", "read", "read_infra", "GET", "/tag/daily/activity"),
    Op("list_guardrails", "read", "read_infra", "GET", "/v2/guardrails/list"),
    Op("guardrail_info", "read", "read_infra", "GET", "/guardrails/{guardrail_id}/info"),
    Op("spend_logs", "read", "read_infra", "GET", "/spend/logs/v2"),
    Op("spend_tags", "read", "read_infra", "GET", "/spend/tags"),
    Op("global_spend_report", "read", "read_infra", "GET", "/global/spend/report"),
    Op("calculate_spend", "read", "read_infra", "POST", "/spend/calculate"),
    Op("cost_estimate", "read", "read_infra", "POST", "/cost/estimate"),
    Op("list_audit_logs", "read", "read_infra", "GET", "/audit"),
    Op("audit_log_info", "read", "read_infra", "GET", "/audit/{id}"),
    Op("health", "read", "read_infra", "GET", "/health"),
    Op("health_readiness", "read", "read_infra", "GET", "/health/readiness"),
    Op("health_services", "read", "read_infra", "GET", "/health/services"),
    Op("active_callbacks", "read", "read_infra", "GET", "/active/callbacks"),
    Op("router_settings", "read", "read_infra", "GET", "/router/settings"),
    Op("get_fallback", "read", "read_infra", "GET", "/fallback/{model}"),
    Op("cache_ping", "read", "read_infra", "GET", "/cache/ping"),
    Op("cache_redis_info", "read", "read_infra", "GET", "/cache/redis/info"),
    Op("cache_settings", "read", "read_infra", "GET", "/cache/settings"),
    Op("sso_settings", "read", "read_infra", "GET", "/get/sso_settings"),
    Op("default_team_settings", "read", "read_infra", "GET", "/get/default_team_settings"),
    Op("internal_user_settings", "read", "read_infra", "GET", "/get/internal_user_settings"),
    Op("email_event_settings", "read", "read_infra", "GET", "/email/event_settings"),
    Op("cost_margin_config", "read", "read_infra", "GET", "/config/cost_margin_config"),
    Op("cost_discount_config", "read", "read_infra", "GET", "/config/cost_discount_config"),
    Op("list_mcp_servers", "read", "read_infra", "GET", "/v1/mcp/server"),
    Op("get_mcp_server", "read", "read_infra", "GET", "/v1/mcp/server/{server_id}"),
    Op("mcp_server_health", "read", "read_infra", "GET", "/v1/mcp/server/health"),
    Op("list_mcp_tools", "read", "read_infra", "GET", "/v1/mcp/tools"),
    Op("mcp_access_groups", "read", "read_infra", "GET", "/v1/mcp/access_groups"),
    Op("list_toolsets", "read", "read_infra", "GET", "/v1/mcp/toolset"),
    Op("get_toolset", "read", "read_infra", "GET", "/v1/mcp/toolset/{toolset_id}"),
    Op("token_counter", "read", "read_infra", "POST", "/utils/token_counter"),
    Op("supported_openai_params", "read", "read_infra", "GET", "/utils/supported_openai_params"),
    Op("list_providers", "read", "read_infra", "GET", "/public/providers"),
    Op("model_cost_map", "read", "read_infra", "GET", "/public/litellm_model_cost_map"),
    # --- write (35) ---
    Op("generate_key", "write", "write", "POST", "/key/generate"),
    Op("update_key", "write", "write", "POST", "/key/update"),
    Op("new_team", "write", "write", "POST", "/team/new"),
    Op("update_team", "write", "write", "POST", "/team/update"),
    Op("team_member_add", "write", "write", "POST", "/team/member_add"),
    Op("team_member_update", "write", "write", "POST", "/team/member_update"),
    Op("team_model_add", "write", "write", "POST", "/team/model/add"),
    Op("team_permissions_update", "write", "write", "POST", "/team/permissions_update"),
    Op("add_team_callback", "write", "write", "POST", "/team/{team_id}/callback"),
    Op("new_user", "write", "write", "POST", "/user/new"),
    Op("update_user", "write", "write", "POST", "/user/update"),
    Op("new_organization", "write", "write", "POST", "/organization/new"),
    Op("update_organization", "write", "write", "PATCH", "/organization/update"),
    Op("organization_member_add", "write", "write", "POST", "/organization/member_add"),
    Op("organization_member_update", "write", "write", "PATCH", "/organization/member_update"),
    Op("new_customer", "write", "write", "POST", "/customer/new"),
    Op("update_customer", "write", "write", "POST", "/customer/update"),
    Op("new_budget", "write", "write", "POST", "/budget/new"),
    Op("update_budget", "write", "write", "POST", "/budget/update"),
    Op("add_model", "write", "write", "POST", "/model/new"),
    Op("update_model", "write", "write", "POST", "/model/update"),
    Op("patch_model", "write", "write", "PATCH", "/model/{model_id}/update"),
    Op("create_access_group", "write", "write", "POST", "/v1/access_group"),
    Op("update_access_group", "write", "write", "PUT", "/v1/access_group/{access_group_id}"),
    Op("create_mcp_server", "write", "write", "POST", "/v1/mcp/server"),
    Op("update_mcp_server", "write", "write", "PUT", "/v1/mcp/server"),
    Op("create_toolset", "write", "write", "POST", "/v1/mcp/toolset"),
    Op("update_toolset", "write", "write", "PUT", "/v1/mcp/toolset"),
    Op("create_credential", "write", "write", "POST", "/credentials"),
    Op("update_credential", "write", "write", "PATCH", "/credentials/{credential_name}"),
    Op("new_tag", "write", "write", "POST", "/tag/new"),
    Op("update_tag", "write", "write", "POST", "/tag/update"),
    Op("create_guardrail", "write", "write", "POST", "/guardrails"),
    Op("update_guardrail", "write", "write", "PUT", "/guardrails/{guardrail_id}"),
    Op("create_fallback", "write", "write", "POST", "/fallback"),
    # --- execute (16) ---
    Op("block_key", "execute", "execute", "POST", "/key/block"),
    Op("unblock_key", "execute", "execute", "POST", "/key/unblock"),
    Op("regenerate_key", "execute", "execute", "POST", "/key/regenerate"),
    Op("reset_key_spend", "execute", "execute", "POST", "/key/{key}/reset_spend"),
    Op("block_team", "execute", "execute", "POST", "/team/block"),
    Op("unblock_team", "execute", "execute", "POST", "/team/unblock"),
    Op("disable_team_logging", "execute", "execute", "POST", "/team/{team_id}/disable_logging"),
    Op("block_model", "execute", "execute", "POST", "/model/block"),
    Op("unblock_model", "execute", "execute", "POST", "/model/unblock"),
    Op("block_customer", "execute", "execute", "POST", "/customer/block"),
    Op("unblock_customer", "execute", "execute", "POST", "/customer/unblock"),
    Op("test_model_connection", "execute", "execute", "POST", "/health/test_connection"),
    Op("test_cache_connection", "execute", "execute", "POST", "/cache/settings/test"),
    Op("test_mcp_connection", "execute", "execute", "POST", "/mcp-rest/test/connection"),
    Op("test_mcp_tools_list", "execute", "execute", "POST", "/mcp-rest/test/tools/list"),
    Op("cache_delete", "execute", "execute", "POST", "/cache/delete"),
    # --- delete (18) ---
    Op("delete_keys", "delete", "delete", "POST", "/key/delete"),
    Op("delete_teams", "delete", "delete", "POST", "/team/delete"),
    Op("team_member_delete", "delete", "delete", "POST", "/team/member_delete"),
    Op("team_model_delete", "delete", "delete", "POST", "/team/model/delete"),
    Op("delete_users", "delete", "delete", "POST", "/user/delete"),
    Op("delete_organizations", "delete", "delete", "DELETE", "/organization/delete"),
    Op("organization_member_delete", "delete", "delete", "DELETE", "/organization/member_delete"),
    Op("delete_customers", "delete", "delete", "POST", "/customer/delete"),
    Op("delete_budget", "delete", "delete", "POST", "/budget/delete"),
    Op("delete_model", "delete", "delete", "POST", "/model/delete"),
    Op("delete_access_group", "delete", "delete", "DELETE", "/v1/access_group/{access_group_id}"),
    Op("delete_mcp_server", "delete", "delete", "DELETE", "/v1/mcp/server/{server_id}"),
    Op("delete_toolset", "delete", "delete", "DELETE", "/v1/mcp/toolset/{toolset_id}"),
    Op("delete_credential", "delete", "delete", "DELETE", "/credentials/{credential_name}"),
    Op("delete_tag", "delete", "delete", "POST", "/tag/delete"),
    Op("delete_guardrail", "delete", "delete", "DELETE", "/guardrails/{guardrail_id}"),
    Op("delete_fallback", "delete", "delete", "DELETE", "/fallback/{model}"),
    Op("cache_flushall", "delete", "delete", "POST", "/cache/flushall"),
    # --- admin (12) ---
    Op("update_sso_settings", "admin", "admin", "PATCH", "/update/sso_settings"),
    Op("update_default_team_settings", "admin", "admin", "PATCH", "/update/default_team_settings"),
    Op("update_internal_user_settings", "admin", "admin", "PATCH", "/update/internal_user_settings"),
    Op("update_email_event_settings", "admin", "admin", "PATCH", "/email/event_settings"),
    Op("reset_email_event_settings", "admin", "admin", "POST", "/email/event_settings/reset"),
    Op("update_cost_margin_config", "admin", "admin", "PATCH", "/config/cost_margin_config"),
    Op("update_cost_discount_config", "admin", "admin", "PATCH", "/config/cost_discount_config"),
    Op("update_cache_settings", "admin", "admin", "POST", "/cache/settings"),
    Op("add_allowed_ip", "admin", "admin", "POST", "/add/allowed_ip"),
    Op("delete_allowed_ip", "admin", "admin", "POST", "/delete/allowed_ip"),
    Op("global_spend_reset", "admin", "admin", "POST", "/global/spend/reset"),
    Op("bulk_update_users", "admin", "admin", "POST", "/user/bulk_update"),
    # --- platform (53): policies / evals / a2a / workflows / cloudzero ---
    Op("list_policies", "read", "platform", "GET", "/policies/list"),
    Op("policy_info", "read", "platform", "GET", "/policies/{policy_id}"),
    Op("list_policy_versions", "read", "platform", "GET", "/policies/name/{policy_name}/versions"),
    Op("compare_policy_versions", "read", "platform", "GET", "/policies/compare"),
    Op("policy_resolved_guardrails", "read", "platform", "GET",
       "/policies/{policy_id}/resolved-guardrails"),
    Op("list_policy_attachments", "read", "platform", "GET", "/policies/attachments/list"),
    Op("policy_attachment_info", "read", "platform", "GET", "/policies/attachments/{attachment_id}"),
    Op("policies_usage_overview", "read", "platform", "GET", "/policies/usage/overview"),
    Op("resolve_policies", "read", "platform", "POST", "/policies/resolve"),
    Op("estimate_attachment_impact", "read", "platform", "POST",
       "/policies/attachments/estimate-impact"),
    Op("create_policy", "write", "platform", "POST", "/policies"),
    Op("update_policy", "write", "platform", "PUT", "/policies/{policy_id}"),
    Op("create_policy_version", "write", "platform", "POST", "/policies/name/{policy_name}/versions"),
    Op("update_policy_version_status", "write", "platform", "PUT", "/policies/{policy_id}/status"),
    Op("create_policy_attachment", "write", "platform", "POST", "/policies/attachments"),
    Op("test_policy_pipeline", "execute", "platform", "POST", "/policies/test-pipeline"),
    Op("delete_policy", "delete", "platform", "DELETE", "/policies/{policy_id}"),
    Op("delete_policy_all_versions", "delete", "platform", "DELETE",
       "/policies/name/{policy_name}/all-versions"),
    Op("delete_policy_attachment", "delete", "platform", "DELETE",
       "/policies/attachments/{attachment_id}"),
    Op("list_evals", "read", "platform", "GET", "/v1/evals"),
    Op("get_eval", "read", "platform", "GET", "/v1/evals/{eval_id}"),
    Op("list_eval_runs", "read", "platform", "GET", "/v1/evals/{eval_id}/runs"),
    Op("get_eval_run", "read", "platform", "GET", "/v1/evals/{eval_id}/runs/{run_id}"),
    Op("create_eval", "write", "platform", "POST", "/v1/evals"),
    Op("update_eval", "write", "platform", "POST", "/v1/evals/{eval_id}"),
    Op("create_eval_run", "write", "platform", "POST", "/v1/evals/{eval_id}/runs"),
    Op("cancel_eval", "execute", "platform", "POST", "/v1/evals/{eval_id}/cancel"),
    Op("cancel_eval_run", "execute", "platform", "POST", "/v1/evals/{eval_id}/runs/{run_id}"),
    Op("delete_eval", "delete", "platform", "DELETE", "/v1/evals/{eval_id}"),
    Op("delete_eval_run", "delete", "platform", "DELETE", "/v1/evals/{eval_id}/runs/{run_id}"),
    Op("list_agents", "read", "platform", "GET", "/v1/agents"),
    Op("get_agent", "read", "platform", "GET", "/v1/agents/{agent_id}"),
    Op("get_agent_card", "read", "platform", "GET",
       "/a2a/{agent_id}/.well-known/agent-card.json"),
    Op("create_agent", "write", "platform", "POST", "/v1/agents"),
    Op("update_agent", "write", "platform", "PUT", "/v1/agents/{agent_id}"),
    Op("patch_agent", "write", "platform", "PATCH", "/v1/agents/{agent_id}"),
    Op("delete_agent", "delete", "platform", "DELETE", "/v1/agents/{agent_id}"),
    Op("agent_daily_activity", "read", "platform", "GET", "/agent/daily/activity"),
    # invoke_agent is an override (JSON-RPC body invisible to the snapshot, Decision 4).
    Op("invoke_agent", "execute", "platform", "POST", "/v1/a2a/{agent_id}/message/send"),
    Op("list_workflow_runs", "read", "platform", "GET", "/v1/workflows/runs"),
    Op("get_workflow_run", "read", "platform", "GET", "/v1/workflows/runs/{run_id}"),
    Op("list_workflow_events", "read", "platform", "GET", "/v1/workflows/runs/{run_id}/events"),
    Op("list_workflow_messages", "read", "platform", "GET", "/v1/workflows/runs/{run_id}/messages"),
    Op("create_workflow_run", "write", "platform", "POST", "/v1/workflows/runs"),
    Op("update_workflow_run", "write", "platform", "PATCH", "/v1/workflows/runs/{run_id}"),
    Op("append_workflow_event", "write", "platform", "POST", "/v1/workflows/runs/{run_id}/events"),
    Op("append_workflow_message", "write", "platform", "POST",
       "/v1/workflows/runs/{run_id}/messages"),
    Op("cloudzero_settings", "read", "platform", "GET", "/cloudzero/settings"),
    Op("cloudzero_dry_run", "read", "platform", "POST", "/cloudzero/dry-run"),
    Op("init_cloudzero", "write", "platform", "POST", "/cloudzero/init"),
    Op("update_cloudzero_settings", "write", "platform", "PUT", "/cloudzero/settings"),
    Op("cloudzero_export", "execute", "platform", "POST", "/cloudzero/export"),
    Op("delete_cloudzero_settings", "delete", "platform", "DELETE", "/cloudzero/delete"),
    # --- prompts (8): Prompt Management CRUD (prompts-and-agent-activity plan) ---
    # update_prompt and test_prompt are overrides (Decisions 11 and 2); test_prompt
    # is execute (a provider call spends money), skipped by the emitter.
    Op("list_prompts", "read", "prompts", "GET", "/prompts/list"),
    Op("get_prompt", "read", "prompts", "GET", "/prompts/{prompt_id}"),
    Op("list_prompt_versions", "read", "prompts", "GET", "/prompts/{prompt_id}/versions"),
    Op("create_prompt", "write", "prompts", "POST", "/prompts"),
    Op("update_prompt", "write", "prompts", "PUT", "/prompts/{prompt_id}"),
    Op("patch_prompt", "write", "prompts", "PATCH", "/prompts/{prompt_id}"),
    Op("delete_prompt", "delete", "prompts", "DELETE", "/prompts/{prompt_id}"),
    Op("test_prompt", "execute", "prompts", "POST", "/prompts/test"),
)

assert len(OPS) == 209, f"expected 209 ops, got {len(OPS)}"

_names = [op.name for op in OPS]
assert len(_names) == len(set(_names)), "duplicate op names in OPS"

OP_BY_NAME: dict[str, Op] = {op.name: op for op in OPS}
