# Generated by codegen/generate.py from openapi-v1.93.0.json. Do not edit.
"""delete tools (generated). Edits are overwritten; change codegen/ instead."""

from __future__ import annotations

from typing import Any, Literal, cast

from ..registry import _UNSET, _op
from .groups import litellm_delete
from .helpers import _get_client, _qp


@_op(litellm_delete)
def cache_flushall() -> Any:
    """Cache Flushall"""
    return _get_client().post("/cache/flushall")


@_op(litellm_delete)
def delete_access_group(
    access_group_id: str,
) -> Any:
    """Delete Access Group"""
    return _get_client().delete(f"/v1/access_group/{access_group_id}")


@_op(litellm_delete)
def delete_budget(
    id: str,
) -> Any:
    """Delete Budget"""
    body: dict[str, Any] = {}
    if id is not _UNSET:
        body["id"] = id
    return _get_client().post("/budget/delete", json=body)


@_op(litellm_delete)
def delete_credential(
    credential_name: str,
) -> Any:
    """Delete Credential"""
    return _get_client().delete(f"/credentials/{credential_name}")


@_op(litellm_delete)
def delete_customers(
    user_ids: list[str],
) -> Any:
    """Delete End User"""
    body: dict[str, Any] = {}
    if user_ids is not _UNSET:
        body["user_ids"] = user_ids
    return _get_client().post("/customer/delete", json=body)


@_op(litellm_delete)
def delete_fallback(
    model: str,
    fallback_type: Literal['general', 'context_window', 'content_policy'] = cast(Literal['general', 'context_window', 'content_policy'], _UNSET),
) -> Any:
    """Delete Fallback"""
    return _get_client().delete(f"/fallback/{model}", params=_qp(fallback_type=fallback_type))


@_op(litellm_delete)
def delete_guardrail(
    guardrail_id: str,
) -> Any:
    """Delete Guardrail"""
    return _get_client().delete(f"/guardrails/{guardrail_id}")


@_op(litellm_delete)
def delete_keys(
    keys: list[str] | None = cast(list[str] | None, _UNSET),
    key_aliases: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Delete Key Fn"""
    body: dict[str, Any] = {}
    if keys is not _UNSET:
        body["keys"] = keys
    if key_aliases is not _UNSET:
        body["key_aliases"] = key_aliases
    return _get_client().post("/key/delete", json=body)


@_op(litellm_delete)
def delete_mcp_server(
    server_id: str,
) -> Any:
    """Remove Mcp Server"""
    return _get_client().delete(f"/v1/mcp/server/{server_id}")


@_op(litellm_delete)
def delete_model(
    id: str,
) -> Any:
    """Delete Model"""
    body: dict[str, Any] = {}
    if id is not _UNSET:
        body["id"] = id
    return _get_client().post("/model/delete", json=body)


@_op(litellm_delete)
def delete_organizations(
    organization_ids: list[str],
) -> Any:
    """Delete Organization"""
    body: dict[str, Any] = {}
    if organization_ids is not _UNSET:
        body["organization_ids"] = organization_ids
    return _get_client().delete("/organization/delete", json=body)


@_op(litellm_delete)
def delete_tag(
    name: str,
) -> Any:
    """Delete Tag"""
    body: dict[str, Any] = {}
    if name is not _UNSET:
        body["name"] = name
    return _get_client().post("/tag/delete", json=body)


@_op(litellm_delete)
def delete_teams(
    team_ids: list[str],
) -> Any:
    """Delete Team"""
    body: dict[str, Any] = {}
    if team_ids is not _UNSET:
        body["team_ids"] = team_ids
    return _get_client().post("/team/delete", json=body)


@_op(litellm_delete)
def delete_toolset(
    toolset_id: str,
) -> Any:
    """Remove Mcp Toolset"""
    return _get_client().delete(f"/v1/mcp/toolset/{toolset_id}")


@_op(litellm_delete)
def delete_users(
    user_ids: list[str],
) -> Any:
    """Delete User"""
    body: dict[str, Any] = {}
    if user_ids is not _UNSET:
        body["user_ids"] = user_ids
    return _get_client().post("/user/delete", json=body)


@_op(litellm_delete)
def organization_member_delete(
    organization_id: str,
    user_id: str | None = cast(str | None, _UNSET),
    user_email: str | None = cast(str | None, _UNSET),
) -> Any:
    """Organization Member Delete"""
    body: dict[str, Any] = {}
    if user_id is not _UNSET:
        body["user_id"] = user_id
    if user_email is not _UNSET:
        body["user_email"] = user_email
    if organization_id is not _UNSET:
        body["organization_id"] = organization_id
    return _get_client().delete("/organization/member_delete", json=body)


@_op(litellm_delete)
def team_member_delete(
    team_id: str,
    user_id: str | None = cast(str | None, _UNSET),
    user_email: str | None = cast(str | None, _UNSET),
) -> Any:
    """Team Member Delete"""
    body: dict[str, Any] = {}
    if user_id is not _UNSET:
        body["user_id"] = user_id
    if user_email is not _UNSET:
        body["user_email"] = user_email
    if team_id is not _UNSET:
        body["team_id"] = team_id
    return _get_client().post("/team/member_delete", json=body)


@_op(litellm_delete)
def team_model_delete(
    team_id: str,
    models: list[str],
) -> Any:
    """Team Model Delete"""
    body: dict[str, Any] = {}
    if team_id is not _UNSET:
        body["team_id"] = team_id
    if models is not _UNSET:
        body["models"] = models
    return _get_client().post("/team/model/delete", json=body)
