# Generated by codegen/generate.py from openapi-v1.93.0.json. Do not edit.
"""read_core tools (generated). Edits are overwritten; change codegen/ instead."""

from __future__ import annotations

from typing import Any, cast

from ..registry import _UNSET, _op
from .groups import litellm_read
from .helpers import _get_client, _qp


@_op(litellm_read)
def budget_info(
    budgets: list[str],
) -> Any:
    """Info Budget"""
    body: dict[str, Any] = {}
    if budgets is not _UNSET:
        body["budgets"] = budgets
    return _get_client().post("/budget/info", json=body)


@_op(litellm_read)
def budget_settings(
    budget_id: str,
) -> Any:
    """Budget Settings"""
    return _get_client().get("/budget/settings", params=_qp(budget_id=budget_id))


@_op(litellm_read)
def customer_daily_activity(
    end_user_ids: str | None = cast(str | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    exclude_end_user_ids: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Customer Daily Activity"""
    return _get_client().get("/customer/daily/activity", params=_qp(end_user_ids=end_user_ids, start_date=start_date, end_date=end_date, model=model, api_key=api_key, page=page, page_size=page_size, exclude_end_user_ids=exclude_end_user_ids))


@_op(litellm_read)
def customer_info(
    end_user_id: str,
) -> Any:
    """End User Info"""
    return _get_client().get("/customer/info", params=_qp(end_user_id=end_user_id))


@_op(litellm_read)
def key_info(
    key: str | None = cast(str | None, _UNSET),
) -> Any:
    """Info Key Fn"""
    return _get_client().get("/key/info", params=_qp(key=key))


@_op(litellm_read)
def list_budgets() -> Any:
    """List Budget"""
    return _get_client().get("/budget/list")


@_op(litellm_read)
def list_customers() -> Any:
    """List End User"""
    return _get_client().get("/customer/list")


@_op(litellm_read)
def list_keys(
    page: int = cast(int, _UNSET),
    size: int = cast(int, _UNSET),
    user_id: str | None = cast(str | None, _UNSET),
    team_id: str | None = cast(str | None, _UNSET),
    organization_id: str | None = cast(str | None, _UNSET),
    key_hash: str | None = cast(str | None, _UNSET),
    key_alias: str | None = cast(str | None, _UNSET),
    return_full_object: bool = cast(bool, _UNSET),
    include_team_keys: bool = cast(bool, _UNSET),
    include_created_by_keys: bool = cast(bool, _UNSET),
    sort_by: str | None = cast(str | None, _UNSET),
    sort_order: str = cast(str, _UNSET),
    expand: list[str] | None = cast(list[str] | None, _UNSET),
    status: str | None = cast(str | None, _UNSET),
    project_id: str | None = cast(str | None, _UNSET),
    access_group_id: str | None = cast(str | None, _UNSET),
    agent_id: str | None = cast(str | None, _UNSET),
    substring_matching: bool = cast(bool, _UNSET),
    expires: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Keys"""
    return _get_client().get("/key/list", params=_qp(page=page, size=size, user_id=user_id, team_id=team_id, organization_id=organization_id, key_hash=key_hash, key_alias=key_alias, return_full_object=return_full_object, include_team_keys=include_team_keys, include_created_by_keys=include_created_by_keys, sort_by=sort_by, sort_order=sort_order, expand=expand, status=status, project_id=project_id, access_group_id=access_group_id, agent_id=agent_id, substring_matching=substring_matching, expires=expires))


@_op(litellm_read)
def list_organizations(
    org_id: str | None = cast(str | None, _UNSET),
    org_alias: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Organization"""
    return _get_client().get("/organization/list", params=_qp(org_id=org_id, org_alias=org_alias))


@_op(litellm_read)
def list_teams(
    user_id: str | None = cast(str | None, _UNSET),
    organization_id: str | None = cast(str | None, _UNSET),
    team_id: str | None = cast(str | None, _UNSET),
    team_alias: str | None = cast(str | None, _UNSET),
    search: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    sort_by: str | None = cast(str | None, _UNSET),
    sort_order: str = cast(str, _UNSET),
    status: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Team V2"""
    return _get_client().get("/v2/team/list", params=_qp(user_id=user_id, organization_id=organization_id, team_id=team_id, team_alias=team_alias, search=search, page=page, page_size=page_size, sort_by=sort_by, sort_order=sort_order, status=status))


@_op(litellm_read)
def list_users(
    role: str | None = cast(str | None, _UNSET),
    user_ids: str | None = cast(str | None, _UNSET),
    sso_user_ids: str | None = cast(str | None, _UNSET),
    user_email: str | None = cast(str | None, _UNSET),
    team: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    sort_by: str | None = cast(str | None, _UNSET),
    sort_order: str = cast(str, _UNSET),
    organization_ids: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Users"""
    return _get_client().get("/user/list", params=_qp(role=role, user_ids=user_ids, sso_user_ids=sso_user_ids, user_email=user_email, team=team, page=page, page_size=page_size, sort_by=sort_by, sort_order=sort_order, organization_ids=organization_ids))


@_op(litellm_read)
def organization_daily_activity(
    organization_ids: str | None = cast(str | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    exclude_organization_ids: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Organization Daily Activity"""
    return _get_client().get("/organization/daily/activity", params=_qp(organization_ids=organization_ids, start_date=start_date, end_date=end_date, model=model, api_key=api_key, page=page, page_size=page_size, exclude_organization_ids=exclude_organization_ids))


@_op(litellm_read)
def organization_info(
    organization_id: str,
) -> Any:
    """Info Organization"""
    return _get_client().get("/organization/info", params=_qp(organization_id=organization_id))


@_op(litellm_read)
def team_callbacks(
    team_id: str,
) -> Any:
    """Get Team Callbacks"""
    return _get_client().get(f"/team/{team_id}/callback")


@_op(litellm_read)
def team_daily_activity(
    team_ids: str | None = cast(str | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    exclude_team_ids: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Team Daily Activity"""
    return _get_client().get("/team/daily/activity", params=_qp(team_ids=team_ids, start_date=start_date, end_date=end_date, model=model, api_key=api_key, page=page, page_size=page_size, exclude_team_ids=exclude_team_ids))


@_op(litellm_read)
def team_info(
    team_id: str = cast(str, _UNSET),
    key_limit: int | None = cast(int | None, _UNSET),
) -> Any:
    """Team Info"""
    return _get_client().get("/team/info", params=_qp(team_id=team_id, key_limit=key_limit))


@_op(litellm_read)
def team_permissions(
    team_id: str = cast(str, _UNSET),
) -> Any:
    """Team Member Permissions"""
    return _get_client().get("/team/permissions_list", params=_qp(team_id=team_id))


@_op(litellm_read)
def user_daily_activity(
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    user_id: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    timezone: int | None = cast(int | None, _UNSET),
) -> Any:
    """Get User Daily Activity"""
    return _get_client().get("/user/daily/activity", params=_qp(start_date=start_date, end_date=end_date, model=model, api_key=api_key, user_id=user_id, page=page, page_size=page_size, timezone=timezone))


@_op(litellm_read)
def user_info(
    user_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """User Info"""
    return _get_client().get("/user/info", params=_qp(user_id=user_id))
