# Generated by codegen/generate.py from openapi-v1.93.0.json. Do not edit.
"""platform tools (generated). Edits are overwritten; change codegen/ instead."""

from __future__ import annotations

from typing import Any, Literal, cast

from ..registry import _UNSET, _op
from .groups import litellm_delete, litellm_execute, litellm_read, litellm_write
from .helpers import _get_client, _qp


@_op(litellm_write)
def append_workflow_event(
    run_id: str,
    event_type: str,
    step_name: str,
    data: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Append Workflow Event"""
    body: dict[str, Any] = {}
    if event_type is not _UNSET:
        body["event_type"] = event_type
    if step_name is not _UNSET:
        body["step_name"] = step_name
    if data is not _UNSET:
        body["data"] = data
    return _get_client().post(f"/v1/workflows/runs/{run_id}/events", json=body)


@_op(litellm_write)
def append_workflow_message(
    run_id: str,
    role: str,
    content: str,
    session_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """Append Workflow Message"""
    body: dict[str, Any] = {}
    if role is not _UNSET:
        body["role"] = role
    if content is not _UNSET:
        body["content"] = content
    if session_id is not _UNSET:
        body["session_id"] = session_id
    return _get_client().post(f"/v1/workflows/runs/{run_id}/messages", json=body)


@_op(litellm_execute)
def cancel_eval(
    eval_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Cancel Eval"""
    return _get_client().post(f"/v1/evals/{eval_id}/cancel", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_execute)
def cancel_eval_run(
    eval_id: str,
    run_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Cancel Run"""
    return _get_client().post(f"/v1/evals/{eval_id}/runs/{run_id}", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_read)
def cloudzero_dry_run(
    limit: int | None = cast(int | None, _UNSET),
    operation: str = cast(str, _UNSET),
    start_time_utc: str | None = cast(str | None, _UNSET),
    end_time_utc: str | None = cast(str | None, _UNSET),
) -> Any:
    """Cloudzero Dry Run Export"""
    body: dict[str, Any] = {}
    if limit is not _UNSET:
        body["limit"] = limit
    if operation is not _UNSET:
        body["operation"] = operation
    if start_time_utc is not _UNSET:
        body["start_time_utc"] = start_time_utc
    if end_time_utc is not _UNSET:
        body["end_time_utc"] = end_time_utc
    return _get_client().post("/cloudzero/dry-run", json=body)


@_op(litellm_execute)
def cloudzero_export(
    limit: int | None = cast(int | None, _UNSET),
    operation: str = cast(str, _UNSET),
    start_time_utc: str | None = cast(str | None, _UNSET),
    end_time_utc: str | None = cast(str | None, _UNSET),
) -> Any:
    """Cloudzero Export"""
    body: dict[str, Any] = {}
    if limit is not _UNSET:
        body["limit"] = limit
    if operation is not _UNSET:
        body["operation"] = operation
    if start_time_utc is not _UNSET:
        body["start_time_utc"] = start_time_utc
    if end_time_utc is not _UNSET:
        body["end_time_utc"] = end_time_utc
    return _get_client().post("/cloudzero/export", json=body)


@_op(litellm_read)
def cloudzero_settings() -> Any:
    """Get Cloudzero Settings"""
    return _get_client().get("/cloudzero/settings")


@_op(litellm_read)
def compare_policy_versions(
    version_a: str,
    version_b: str,
) -> Any:
    """Compare Policy Versions"""
    return _get_client().get("/policies/compare", params=_qp(version_a=version_a, version_b=version_b))


@_op(litellm_write)
def create_agent(
    agent_name: str,
    agent_card_params: dict[str, Any],
    litellm_params: dict[str, Any] = cast(dict[str, Any], _UNSET),
    object_permission: dict[str, Any] = cast(dict[str, Any], _UNSET),
    tpm_limit: int | None = cast(int | None, _UNSET),
    rpm_limit: int | None = cast(int | None, _UNSET),
    session_tpm_limit: int | None = cast(int | None, _UNSET),
    session_rpm_limit: int | None = cast(int | None, _UNSET),
    static_headers: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    extra_headers: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Create Agent"""
    body: dict[str, Any] = {}
    if agent_name is not _UNSET:
        body["agent_name"] = agent_name
    if agent_card_params is not _UNSET:
        body["agent_card_params"] = agent_card_params
    if litellm_params is not _UNSET:
        body["litellm_params"] = litellm_params
    if object_permission is not _UNSET:
        body["object_permission"] = object_permission
    if tpm_limit is not _UNSET:
        body["tpm_limit"] = tpm_limit
    if rpm_limit is not _UNSET:
        body["rpm_limit"] = rpm_limit
    if session_tpm_limit is not _UNSET:
        body["session_tpm_limit"] = session_tpm_limit
    if session_rpm_limit is not _UNSET:
        body["session_rpm_limit"] = session_rpm_limit
    if static_headers is not _UNSET:
        body["static_headers"] = static_headers
    if extra_headers is not _UNSET:
        body["extra_headers"] = extra_headers
    return _get_client().post("/v1/agents", json=body)


@_op(litellm_write)
def create_policy(
    policy_name: str,
    inherit: str | None = cast(str | None, _UNSET),
    description: str | None = cast(str | None, _UNSET),
    guardrails_add: list[str] | None = cast(list[str] | None, _UNSET),
    guardrails_remove: list[str] | None = cast(list[str] | None, _UNSET),
    condition: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    pipeline: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Create Policy"""
    body: dict[str, Any] = {}
    if policy_name is not _UNSET:
        body["policy_name"] = policy_name
    if inherit is not _UNSET:
        body["inherit"] = inherit
    if description is not _UNSET:
        body["description"] = description
    if guardrails_add is not _UNSET:
        body["guardrails_add"] = guardrails_add
    if guardrails_remove is not _UNSET:
        body["guardrails_remove"] = guardrails_remove
    if condition is not _UNSET:
        body["condition"] = condition
    if pipeline is not _UNSET:
        body["pipeline"] = pipeline
    return _get_client().post("/policies", json=body)


@_op(litellm_write)
def create_policy_attachment(
    policy_name: str,
    scope: str | None = cast(str | None, _UNSET),
    teams: list[str] | None = cast(list[str] | None, _UNSET),
    keys: list[str] | None = cast(list[str] | None, _UNSET),
    models: list[str] | None = cast(list[str] | None, _UNSET),
    tags: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Create Policy Attachment"""
    body: dict[str, Any] = {}
    if policy_name is not _UNSET:
        body["policy_name"] = policy_name
    if scope is not _UNSET:
        body["scope"] = scope
    if teams is not _UNSET:
        body["teams"] = teams
    if keys is not _UNSET:
        body["keys"] = keys
    if models is not _UNSET:
        body["models"] = models
    if tags is not _UNSET:
        body["tags"] = tags
    return _get_client().post("/policies/attachments", json=body)


@_op(litellm_write)
def create_policy_version(
    policy_name: str,
    source_policy_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """Create Policy Version"""
    body: dict[str, Any] = {}
    if source_policy_id is not _UNSET:
        body["source_policy_id"] = source_policy_id
    return _get_client().post(f"/policies/name/{policy_name}/versions", json=body)


@_op(litellm_write)
def create_workflow_run(
    workflow_type: str,
    input: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    metadata: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Create Workflow Run"""
    body: dict[str, Any] = {}
    if workflow_type is not _UNSET:
        body["workflow_type"] = workflow_type
    if input is not _UNSET:
        body["input"] = input
    if metadata is not _UNSET:
        body["metadata"] = metadata
    return _get_client().post("/v1/workflows/runs", json=body)


@_op(litellm_delete)
def delete_cloudzero_settings() -> Any:
    """Delete Cloudzero Settings"""
    return _get_client().delete("/cloudzero/delete")


@_op(litellm_delete)
def delete_eval(
    eval_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Delete Eval"""
    return _get_client().delete(f"/v1/evals/{eval_id}", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_delete)
def delete_eval_run(
    eval_id: str,
    run_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Delete Run"""
    return _get_client().delete(f"/v1/evals/{eval_id}/runs/{run_id}", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_delete)
def delete_policy(
    policy_id: str,
) -> Any:
    """Delete Policy"""
    return _get_client().delete(f"/policies/{policy_id}")


@_op(litellm_delete)
def delete_policy_all_versions(
    policy_name: str,
) -> Any:
    """Delete All Policy Versions"""
    return _get_client().delete(f"/policies/name/{policy_name}/all-versions")


@_op(litellm_delete)
def delete_policy_attachment(
    attachment_id: str,
) -> Any:
    """Delete Policy Attachment"""
    return _get_client().delete(f"/policies/attachments/{attachment_id}")


@_op(litellm_read)
def estimate_attachment_impact(
    policy_name: str,
    scope: str | None = cast(str | None, _UNSET),
    teams: list[str] | None = cast(list[str] | None, _UNSET),
    keys: list[str] | None = cast(list[str] | None, _UNSET),
    models: list[str] | None = cast(list[str] | None, _UNSET),
    tags: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Estimate Attachment Impact"""
    body: dict[str, Any] = {}
    if policy_name is not _UNSET:
        body["policy_name"] = policy_name
    if scope is not _UNSET:
        body["scope"] = scope
    if teams is not _UNSET:
        body["teams"] = teams
    if keys is not _UNSET:
        body["keys"] = keys
    if models is not _UNSET:
        body["models"] = models
    if tags is not _UNSET:
        body["tags"] = tags
    return _get_client().post("/policies/attachments/estimate-impact", json=body)


@_op(litellm_read)
def get_agent(
    agent_id: str,
) -> Any:
    """Get Agent By Id"""
    return _get_client().get(f"/v1/agents/{agent_id}")


@_op(litellm_read)
def get_agent_card(
    agent_id: str,
) -> Any:
    """Get Agent Card"""
    return _get_client().get(f"/a2a/{agent_id}/.well-known/agent-card.json")


@_op(litellm_read)
def get_eval(
    eval_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Eval"""
    return _get_client().get(f"/v1/evals/{eval_id}", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_read)
def get_eval_run(
    eval_id: str,
    run_id: str,
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Run"""
    return _get_client().get(f"/v1/evals/{eval_id}/runs/{run_id}", params=_qp(custom_llm_provider=custom_llm_provider))


@_op(litellm_read)
def get_workflow_run(
    run_id: str,
) -> Any:
    """Get Workflow Run"""
    return _get_client().get(f"/v1/workflows/runs/{run_id}")


@_op(litellm_write)
def init_cloudzero(
    api_key: str,
    connection_id: str,
    timezone: str = cast(str, _UNSET),
) -> Any:
    """Init Cloudzero Settings"""
    body: dict[str, Any] = {}
    if api_key is not _UNSET:
        body["api_key"] = api_key
    if connection_id is not _UNSET:
        body["connection_id"] = connection_id
    if timezone is not _UNSET:
        body["timezone"] = timezone
    return _get_client().post("/cloudzero/init", json=body)


@_op(litellm_read)
def list_agents(
    health_check: bool = cast(bool, _UNSET),
) -> Any:
    """Get Agents"""
    return _get_client().get("/v1/agents", params=_qp(health_check=health_check))


@_op(litellm_read)
def list_eval_runs(
    eval_id: str,
    limit: int | None = cast(int | None, _UNSET),
    after: str | None = cast(str | None, _UNSET),
    before: str | None = cast(str | None, _UNSET),
    order: str | None = cast(str | None, _UNSET),
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Runs"""
    return _get_client().get(f"/v1/evals/{eval_id}/runs", params=_qp(limit=limit, after=after, before=before, order=order, custom_llm_provider=custom_llm_provider))


@_op(litellm_read)
def list_evals(
    limit: int | None = cast(int | None, _UNSET),
    after: str | None = cast(str | None, _UNSET),
    before: str | None = cast(str | None, _UNSET),
    order: str | None = cast(str | None, _UNSET),
    order_by: str | None = cast(str | None, _UNSET),
    custom_llm_provider: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Evals"""
    return _get_client().get("/v1/evals", params=_qp(limit=limit, after=after, before=before, order=order, order_by=order_by, custom_llm_provider=custom_llm_provider))


@_op(litellm_read)
def list_policies(
    version_status: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Policies"""
    return _get_client().get("/policies/list", params=_qp(version_status=version_status))


@_op(litellm_read)
def list_policy_attachments() -> Any:
    """List Policy Attachments"""
    return _get_client().get("/policies/attachments/list")


@_op(litellm_read)
def list_policy_versions(
    policy_name: str,
) -> Any:
    """List Policy Versions"""
    return _get_client().get(f"/policies/name/{policy_name}/versions")


@_op(litellm_read)
def list_workflow_events(
    run_id: str,
    limit: int = cast(int, _UNSET),
) -> Any:
    """List Workflow Events"""
    return _get_client().get(f"/v1/workflows/runs/{run_id}/events", params=_qp(limit=limit))


@_op(litellm_read)
def list_workflow_messages(
    run_id: str,
    limit: int = cast(int, _UNSET),
) -> Any:
    """List Workflow Messages"""
    return _get_client().get(f"/v1/workflows/runs/{run_id}/messages", params=_qp(limit=limit))


@_op(litellm_read)
def list_workflow_runs(
    workflow_type: str | None = cast(str | None, _UNSET),
    status: str | None = cast(str | None, _UNSET),
    limit: int = cast(int, _UNSET),
) -> Any:
    """List Workflow Runs"""
    return _get_client().get("/v1/workflows/runs", params=_qp(workflow_type=workflow_type, status=status, limit=limit))


@_op(litellm_write)
def patch_agent(
    agent_id: str,
    agent_name: str = cast(str, _UNSET),
    agent_card_params: dict[str, Any] = cast(dict[str, Any], _UNSET),
    litellm_params: dict[str, Any] = cast(dict[str, Any], _UNSET),
    object_permission: dict[str, Any] = cast(dict[str, Any], _UNSET),
    tpm_limit: int | None = cast(int | None, _UNSET),
    rpm_limit: int | None = cast(int | None, _UNSET),
    session_tpm_limit: int | None = cast(int | None, _UNSET),
    session_rpm_limit: int | None = cast(int | None, _UNSET),
    static_headers: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    extra_headers: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Patch Agent"""
    body: dict[str, Any] = {}
    if agent_name is not _UNSET:
        body["agent_name"] = agent_name
    if agent_card_params is not _UNSET:
        body["agent_card_params"] = agent_card_params
    if litellm_params is not _UNSET:
        body["litellm_params"] = litellm_params
    if object_permission is not _UNSET:
        body["object_permission"] = object_permission
    if tpm_limit is not _UNSET:
        body["tpm_limit"] = tpm_limit
    if rpm_limit is not _UNSET:
        body["rpm_limit"] = rpm_limit
    if session_tpm_limit is not _UNSET:
        body["session_tpm_limit"] = session_tpm_limit
    if session_rpm_limit is not _UNSET:
        body["session_rpm_limit"] = session_rpm_limit
    if static_headers is not _UNSET:
        body["static_headers"] = static_headers
    if extra_headers is not _UNSET:
        body["extra_headers"] = extra_headers
    return _get_client().patch(f"/v1/agents/{agent_id}", json=body)


@_op(litellm_read)
def policies_usage_overview(
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
) -> Any:
    """Policies Usage Overview"""
    return _get_client().get("/policies/usage/overview", params=_qp(start_date=start_date, end_date=end_date))


@_op(litellm_read)
def policy_attachment_info(
    attachment_id: str,
) -> Any:
    """Get Policy Attachment"""
    return _get_client().get(f"/policies/attachments/{attachment_id}")


@_op(litellm_read)
def policy_info(
    policy_id: str,
) -> Any:
    """Get Policy"""
    return _get_client().get(f"/policies/{policy_id}")


@_op(litellm_read)
def policy_resolved_guardrails(
    policy_id: str,
) -> Any:
    """Get Resolved Guardrails"""
    return _get_client().get(f"/policies/{policy_id}/resolved-guardrails")


@_op(litellm_read)
def resolve_policies(
    key_alias: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    tags: list[str] | None = cast(list[str] | None, _UNSET),
    team_alias: str | None = cast(str | None, _UNSET),
    force_sync: bool = cast(bool, _UNSET),
) -> Any:
    """Resolve Policies For Context"""
    body: dict[str, Any] = {}
    if key_alias is not _UNSET:
        body["key_alias"] = key_alias
    if model is not _UNSET:
        body["model"] = model
    if tags is not _UNSET:
        body["tags"] = tags
    if team_alias is not _UNSET:
        body["team_alias"] = team_alias
    return _get_client().post("/policies/resolve", params=_qp(force_sync=force_sync), json=body)


@_op(litellm_execute)
def test_policy_pipeline(
    pipeline: dict[str, Any],
    test_messages: list[dict[str, Any]],
) -> Any:
    """Test Pipeline"""
    body: dict[str, Any] = {}
    if pipeline is not _UNSET:
        body["pipeline"] = pipeline
    if test_messages is not _UNSET:
        body["test_messages"] = test_messages
    return _get_client().post("/policies/test-pipeline", json=body)


@_op(litellm_write)
def update_agent(
    agent_id: str,
    agent_name: str,
    agent_card_params: dict[str, Any],
    litellm_params: dict[str, Any] = cast(dict[str, Any], _UNSET),
    object_permission: dict[str, Any] = cast(dict[str, Any], _UNSET),
    tpm_limit: int | None = cast(int | None, _UNSET),
    rpm_limit: int | None = cast(int | None, _UNSET),
    session_tpm_limit: int | None = cast(int | None, _UNSET),
    session_rpm_limit: int | None = cast(int | None, _UNSET),
    static_headers: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    extra_headers: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Update Agent"""
    body: dict[str, Any] = {}
    if agent_name is not _UNSET:
        body["agent_name"] = agent_name
    if agent_card_params is not _UNSET:
        body["agent_card_params"] = agent_card_params
    if litellm_params is not _UNSET:
        body["litellm_params"] = litellm_params
    if object_permission is not _UNSET:
        body["object_permission"] = object_permission
    if tpm_limit is not _UNSET:
        body["tpm_limit"] = tpm_limit
    if rpm_limit is not _UNSET:
        body["rpm_limit"] = rpm_limit
    if session_tpm_limit is not _UNSET:
        body["session_tpm_limit"] = session_tpm_limit
    if session_rpm_limit is not _UNSET:
        body["session_rpm_limit"] = session_rpm_limit
    if static_headers is not _UNSET:
        body["static_headers"] = static_headers
    if extra_headers is not _UNSET:
        body["extra_headers"] = extra_headers
    return _get_client().put(f"/v1/agents/{agent_id}", json=body)


@_op(litellm_write)
def update_cloudzero_settings(
    api_key: str | None = cast(str | None, _UNSET),
    connection_id: str | None = cast(str | None, _UNSET),
    timezone: str | None = cast(str | None, _UNSET),
) -> Any:
    """Update Cloudzero Settings"""
    body: dict[str, Any] = {}
    if api_key is not _UNSET:
        body["api_key"] = api_key
    if connection_id is not _UNSET:
        body["connection_id"] = connection_id
    if timezone is not _UNSET:
        body["timezone"] = timezone
    return _get_client().put("/cloudzero/settings", json=body)


@_op(litellm_write)
def update_policy(
    policy_id: str,
    policy_name: str | None = cast(str | None, _UNSET),
    inherit: str | None = cast(str | None, _UNSET),
    description: str | None = cast(str | None, _UNSET),
    guardrails_add: list[str] | None = cast(list[str] | None, _UNSET),
    guardrails_remove: list[str] | None = cast(list[str] | None, _UNSET),
    condition: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    pipeline: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Update Policy"""
    body: dict[str, Any] = {}
    if policy_name is not _UNSET:
        body["policy_name"] = policy_name
    if inherit is not _UNSET:
        body["inherit"] = inherit
    if description is not _UNSET:
        body["description"] = description
    if guardrails_add is not _UNSET:
        body["guardrails_add"] = guardrails_add
    if guardrails_remove is not _UNSET:
        body["guardrails_remove"] = guardrails_remove
    if condition is not _UNSET:
        body["condition"] = condition
    if pipeline is not _UNSET:
        body["pipeline"] = pipeline
    return _get_client().put(f"/policies/{policy_id}", json=body)


@_op(litellm_write)
def update_policy_version_status(
    policy_id: str,
    version_status: str,
) -> Any:
    """Update Policy Version Status"""
    body: dict[str, Any] = {}
    if version_status is not _UNSET:
        body["version_status"] = version_status
    return _get_client().put(f"/policies/{policy_id}/status", json=body)


@_op(litellm_write)
def update_workflow_run(
    run_id: str,
    status: Literal['pending', 'running', 'paused', 'completed', 'failed'] | None = cast(Literal['pending', 'running', 'paused', 'completed', 'failed'] | None, _UNSET),
    output: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
    metadata: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Update Workflow Run"""
    body: dict[str, Any] = {}
    if status is not _UNSET:
        body["status"] = status
    if output is not _UNSET:
        body["output"] = output
    if metadata is not _UNSET:
        body["metadata"] = metadata
    return _get_client().patch(f"/v1/workflows/runs/{run_id}", json=body)
