# Generated by codegen/generate.py from openapi-v1.93.0.json. Do not edit.
"""read_infra tools (generated). Edits are overwritten; change codegen/ instead."""

from __future__ import annotations

from typing import Any, Literal, cast

from ..registry import _UNSET, _op
from .groups import litellm_read
from .helpers import _get_client, _qp


@_op(litellm_read)
def access_group_info(
    access_group_id: str,
) -> Any:
    """Get Access Group"""
    return _get_client().get(f"/v1/access_group/{access_group_id}")


@_op(litellm_read)
def active_callbacks() -> Any:
    """Active Callbacks"""
    return _get_client().get("/active/callbacks")


@_op(litellm_read)
def audit_log_info(
    id: str,
) -> Any:
    """Get Audit Log By Id"""
    return _get_client().get(f"/audit/{id}")


@_op(litellm_read)
def cache_ping() -> Any:
    """Cache Ping"""
    return _get_client().get("/cache/ping")


@_op(litellm_read)
def cache_redis_info() -> Any:
    """Cache Redis Info"""
    return _get_client().get("/cache/redis/info")


@_op(litellm_read)
def cache_settings() -> Any:
    """Get Cache Settings"""
    return _get_client().get("/cache/settings")


@_op(litellm_read)
def calculate_spend(
    model: str | None = cast(str | None, _UNSET),
    messages: list[Any] | None = cast(list[Any] | None, _UNSET),
    completion_response: dict[str, Any] | None = cast(dict[str, Any] | None, _UNSET),
) -> Any:
    """Calculate Spend"""
    body: dict[str, Any] = {}
    if model is not _UNSET:
        body["model"] = model
    if messages is not _UNSET:
        body["messages"] = messages
    if completion_response is not _UNSET:
        body["completion_response"] = completion_response
    return _get_client().post("/spend/calculate", json=body)


@_op(litellm_read)
def cost_discount_config() -> Any:
    """Get Cost Discount Config"""
    return _get_client().get("/config/cost_discount_config")


@_op(litellm_read)
def cost_estimate(
    model: str,
    input_tokens: int,
    output_tokens: int,
    num_requests_per_day: int | None = cast(int | None, _UNSET),
    num_requests_per_month: int | None = cast(int | None, _UNSET),
) -> Any:
    """Estimate Cost"""
    body: dict[str, Any] = {}
    if model is not _UNSET:
        body["model"] = model
    if input_tokens is not _UNSET:
        body["input_tokens"] = input_tokens
    if output_tokens is not _UNSET:
        body["output_tokens"] = output_tokens
    if num_requests_per_day is not _UNSET:
        body["num_requests_per_day"] = num_requests_per_day
    if num_requests_per_month is not _UNSET:
        body["num_requests_per_month"] = num_requests_per_month
    return _get_client().post("/cost/estimate", json=body)


@_op(litellm_read)
def cost_margin_config() -> Any:
    """Get Cost Margin Config"""
    return _get_client().get("/config/cost_margin_config")


@_op(litellm_read)
def credential_by_model(
    model_id: str,
) -> Any:
    """Get Credential By Model"""
    return _get_client().get(f"/credentials/by_model/{model_id}")


@_op(litellm_read)
def default_team_settings() -> Any:
    """Get Default Team Settings"""
    return _get_client().get("/get/default_team_settings")


@_op(litellm_read)
def email_event_settings() -> Any:
    """Get Email Event Settings"""
    return _get_client().get("/email/event_settings")


@_op(litellm_read)
def get_credential(
    credential_name: str,
) -> Any:
    """Get Credential By Name"""
    return _get_client().get(f"/credentials/by_name/{credential_name}")


@_op(litellm_read)
def get_fallback(
    model: str,
    fallback_type: Literal['general', 'context_window', 'content_policy'] = cast(Literal['general', 'context_window', 'content_policy'], _UNSET),
) -> Any:
    """Get Fallback"""
    return _get_client().get(f"/fallback/{model}", params=_qp(fallback_type=fallback_type))


@_op(litellm_read)
def get_mcp_server(
    server_id: str,
) -> Any:
    """Fetch Mcp Server"""
    return _get_client().get(f"/v1/mcp/server/{server_id}")


@_op(litellm_read)
def get_model(
    model_id: str,
    team_id: str | None = cast(str | None, _UNSET),
    healthy_only: bool | None = cast(bool | None, _UNSET),
) -> Any:
    """Model Info"""
    return _get_client().get(f"/v1/models/{model_id}", params=_qp(team_id=team_id, healthy_only=healthy_only))


@_op(litellm_read)
def get_toolset(
    toolset_id: str,
) -> Any:
    """Fetch Mcp Toolset"""
    return _get_client().get(f"/v1/mcp/toolset/{toolset_id}")


@_op(litellm_read)
def global_spend_report(
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    group_by: Literal['team', 'customer', 'api_key'] | None = cast(Literal['team', 'customer', 'api_key'] | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    internal_user_id: str | None = cast(str | None, _UNSET),
    team_id: str | None = cast(str | None, _UNSET),
    customer_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """Get Global Spend Report"""
    return _get_client().get("/global/spend/report", params=_qp(start_date=start_date, end_date=end_date, group_by=group_by, api_key=api_key, internal_user_id=internal_user_id, team_id=team_id, customer_id=customer_id))


@_op(litellm_read)
def guardrail_info(
    guardrail_id: str,
) -> Any:
    """Get Guardrail Info"""
    return _get_client().get(f"/guardrails/{guardrail_id}/info")


@_op(litellm_read)
def health(
    model: str | None = cast(str | None, _UNSET),
    model_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """Health Endpoint"""
    return _get_client().get("/health", params=_qp(model=model, model_id=model_id))


@_op(litellm_read)
def health_readiness() -> Any:
    """Health Readiness"""
    return _get_client().get("/health/readiness")


@_op(litellm_read)
def health_services(
    service: Literal['slack_budget_alerts', 'langfuse', 'langfuse_otel', 'slack', 'openmeter', 'webhook', 'email', 'braintrust', 'datadog', 'datadog_llm_observability', 'generic_api', 'arize', 'galileo', 'newrelic', 'sqs'] | str,
) -> Any:
    """Health Services Endpoint"""
    return _get_client().get("/health/services", params=_qp(service=service))


@_op(litellm_read)
def internal_user_settings() -> Any:
    """Get Internal User Settings"""
    return _get_client().get("/get/internal_user_settings")


@_op(litellm_read)
def list_access_groups() -> Any:
    """List Access Groups"""
    return _get_client().get("/v1/access_group")


@_op(litellm_read)
def list_audit_logs(
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    changed_by: str | None = cast(str | None, _UNSET),
    changed_by_api_key: str | None = cast(str | None, _UNSET),
    action: str | None = cast(str | None, _UNSET),
    table_name: str | None = cast(str | None, _UNSET),
    object_id: str | None = cast(str | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    object_team_id: str | None = cast(str | None, _UNSET),
    object_key_hash: str | None = cast(str | None, _UNSET),
    sort_by: str | None = cast(str | None, _UNSET),
    sort_order: str = cast(str, _UNSET),
) -> Any:
    """Get Audit Logs"""
    return _get_client().get("/audit", params=_qp(page=page, page_size=page_size, changed_by=changed_by, changed_by_api_key=changed_by_api_key, action=action, table_name=table_name, object_id=object_id, start_date=start_date, end_date=end_date, object_team_id=object_team_id, object_key_hash=object_key_hash, sort_by=sort_by, sort_order=sort_order))


@_op(litellm_read)
def list_credentials() -> Any:
    """Get Credentials"""
    return _get_client().get("/credentials")


@_op(litellm_read)
def list_guardrails() -> Any:
    """List Guardrails V2"""
    return _get_client().get("/v2/guardrails/list")


@_op(litellm_read)
def list_mcp_servers(
    team_id: str | None = cast(str | None, _UNSET),
) -> Any:
    """Fetch All Mcp Servers"""
    return _get_client().get("/v1/mcp/server", params=_qp(team_id=team_id))


@_op(litellm_read)
def list_mcp_tools() -> Any:
    """Get Mcp Tools"""
    return _get_client().get("/v1/mcp/tools")


@_op(litellm_read)
def list_models(
    return_wildcard_routes: bool | None = cast(bool | None, _UNSET),
    team_id: str | None = cast(str | None, _UNSET),
    include_model_access_groups: bool | None = cast(bool | None, _UNSET),
    only_model_access_groups: bool | None = cast(bool | None, _UNSET),
    include_metadata: bool | None = cast(bool | None, _UNSET),
    fallback_type: str | None = cast(str | None, _UNSET),
    scope: str | None = cast(str | None, _UNSET),
    healthy_only: bool | None = cast(bool | None, _UNSET),
) -> Any:
    """Model List"""
    return _get_client().get("/v1/models", params=_qp(return_wildcard_routes=return_wildcard_routes, team_id=team_id, include_model_access_groups=include_model_access_groups, only_model_access_groups=only_model_access_groups, include_metadata=include_metadata, fallback_type=fallback_type, scope=scope, healthy_only=healthy_only))


@_op(litellm_read)
def list_providers() -> Any:
    """Get Supported Providers"""
    return _get_client().get("/public/providers")


@_op(litellm_read)
def list_tags(
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
) -> Any:
    """List Tags"""
    return _get_client().get("/tag/list", params=_qp(start_date=start_date, end_date=end_date))


@_op(litellm_read)
def list_toolsets() -> Any:
    """Fetch Mcp Toolsets"""
    return _get_client().get("/v1/mcp/toolset")


@_op(litellm_read)
def mcp_access_groups() -> Any:
    """Get Mcp Access Groups"""
    return _get_client().get("/v1/mcp/access_groups")


@_op(litellm_read)
def mcp_server_health(
    server_ids: list[str] | None = cast(list[str] | None, _UNSET),
) -> Any:
    """Health Check Servers"""
    return _get_client().get("/v1/mcp/server/health", params=_qp(server_ids=server_ids))


@_op(litellm_read)
def model_cost_map() -> Any:
    """Get Litellm Model Cost Map"""
    return _get_client().get("/public/litellm_model_cost_map")


@_op(litellm_read)
def model_group_info(
    model_group: str | None = cast(str | None, _UNSET),
) -> Any:
    """Model Group Info"""
    return _get_client().get("/model_group/info", params=_qp(model_group=model_group))


@_op(litellm_read)
def model_info(
    model: str | None = cast(str | None, _UNSET),
    user_models_only: bool | None = cast(bool | None, _UNSET),
    include_team_models: bool | None = cast(bool | None, _UNSET),
    debug: bool | None = cast(bool | None, _UNSET),
    page: int = cast(int, _UNSET),
    size: int = cast(int, _UNSET),
    search: str | None = cast(str | None, _UNSET),
    modelId: str | None = cast(str | None, _UNSET),
    teamId: str | None = cast(str | None, _UNSET),
    sortBy: str | None = cast(str | None, _UNSET),
    sortOrder: str | None = cast(str | None, _UNSET),
) -> Any:
    """Model Info V2"""
    return _get_client().get("/v2/model/info", params=_qp(model=model, user_models_only=user_models_only, include_team_models=include_team_models, debug=debug, page=page, size=size, search=search, modelId=modelId, teamId=teamId, sortBy=sortBy, sortOrder=sortOrder))


@_op(litellm_read)
def router_settings() -> Any:
    """Get Router Settings"""
    return _get_client().get("/router/settings")


@_op(litellm_read)
def spend_logs(
    api_key: str | None = cast(str | None, _UNSET),
    user_id: str | None = cast(str | None, _UNSET),
    request_id: str | None = cast(str | None, _UNSET),
    session_id: str | None = cast(str | None, _UNSET),
    team_id: str | None = cast(str | None, _UNSET),
    min_spend: float | None = cast(float | None, _UNSET),
    max_spend: float | None = cast(float | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
    status_filter: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    model_id: str | None = cast(str | None, _UNSET),
    model_group: str | None = cast(str | None, _UNSET),
    key_alias: str | None = cast(str | None, _UNSET),
    end_user: str | None = cast(str | None, _UNSET),
    error_code: str | None = cast(str | None, _UNSET),
    error_message: str | None = cast(str | None, _UNSET),
    sort_by: str = cast(str, _UNSET),
    sort_order: str | None = cast(str | None, _UNSET),
) -> Any:
    """Ui View Spend Logs"""
    return _get_client().get("/spend/logs/v2", params=_qp(api_key=api_key, user_id=user_id, request_id=request_id, session_id=session_id, team_id=team_id, min_spend=min_spend, max_spend=max_spend, start_date=start_date, end_date=end_date, page=page, page_size=page_size, status_filter=status_filter, model=model, model_id=model_id, model_group=model_group, key_alias=key_alias, end_user=end_user, error_code=error_code, error_message=error_message, sort_by=sort_by, sort_order=sort_order))


@_op(litellm_read)
def spend_tags(
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
) -> Any:
    """View Spend Tags"""
    return _get_client().get("/spend/tags", params=_qp(start_date=start_date, end_date=end_date))


@_op(litellm_read)
def sso_settings() -> Any:
    """Get Sso Settings"""
    return _get_client().get("/get/sso_settings")


@_op(litellm_read)
def supported_openai_params(
    model: str,
) -> Any:
    """Supported Openai Params"""
    return _get_client().get("/utils/supported_openai_params", params=_qp(model=model))


@_op(litellm_read)
def tag_daily_activity(
    tags: str | None = cast(str | None, _UNSET),
    start_date: str | None = cast(str | None, _UNSET),
    end_date: str | None = cast(str | None, _UNSET),
    model: str | None = cast(str | None, _UNSET),
    api_key: str | None = cast(str | None, _UNSET),
    page: int = cast(int, _UNSET),
    page_size: int = cast(int, _UNSET),
) -> Any:
    """Get Tag Daily Activity"""
    return _get_client().get("/tag/daily/activity", params=_qp(tags=tags, start_date=start_date, end_date=end_date, model=model, api_key=api_key, page=page, page_size=page_size))


@_op(litellm_read)
def tag_info(
    names: list[str],
) -> Any:
    """Info Tag"""
    body: dict[str, Any] = {}
    if names is not _UNSET:
        body["names"] = names
    return _get_client().post("/tag/info", json=body)


@_op(litellm_read)
def token_counter(
    model: str,
    prompt: str | None = cast(str | None, _UNSET),
    messages: list[dict[str, Any]] | None = cast(list[dict[str, Any]] | None, _UNSET),
    contents: list[dict[str, Any]] | None = cast(list[dict[str, Any]] | None, _UNSET),
    tools: list[dict[str, Any]] | None = cast(list[dict[str, Any]] | None, _UNSET),
    system: Any = cast(Any, _UNSET),
    call_endpoint: bool = cast(bool, _UNSET),
) -> Any:
    """Token Counter"""
    body: dict[str, Any] = {}
    if model is not _UNSET:
        body["model"] = model
    if prompt is not _UNSET:
        body["prompt"] = prompt
    if messages is not _UNSET:
        body["messages"] = messages
    if contents is not _UNSET:
        body["contents"] = contents
    if tools is not _UNSET:
        body["tools"] = tools
    if system is not _UNSET:
        body["system"] = system
    return _get_client().post("/utils/token_counter", params=_qp(call_endpoint=call_endpoint), json=body)
